### ISSUE TITLE
我十几兆的处理之后变成30多兆了

### ISSUE THREAD

**Issue by anandyuan** [renzhezhilu/webp2jpg-online#11]
![image](https://user-images.githubusercontent.com/55307207/88250012-cf3b6580-ccd8-11ea-9cdc-8e581a751a02.png)

**Comment by renzhezhilu** [comment]
不支持png压缩
你可以试试这个
https://tinypng.com/

**Comment by renzhezhilu** [comment]
新版本v3已经支持png压缩，格式选择`png-tiny`即可
