### ISSUE TITLE
默认环境没有处理图片，需要环境开启哪些扩展呢？

### ISSUE THREAD

**Issue by topkof** [renzhezhilu/webp2jpg-online#22]
BT面板环境php7.4，开启了imagemagick扩展，但上传图片后并没有处理，图片一为我的环境，第二张图片为您官方测试地址
![QQ截图20210109232706](https://user-images.githubusercontent.com/26196829/104095601-b8aeb800-52d2-11eb-887a-1456dcaa8c05.png)

![QQ截图20210109232832](https://user-images.githubusercontent.com/26196829/104095603-ba787b80-52d2-11eb-88de-76f59bbd6283.png)

**Comment by love2wind** [comment]
同问

**Comment by omegacc91** [comment]
同问

**Comment by afengim** [comment]
同问！！！求大佬解答

**Comment by renzhezhilu** [comment]
不好意思，现在只能在指定的网页运行，如果你想了解原理看这个，有详细的demo [https://github.com/renzhezhilu/browser-image-conversion-dome](https://github.com/renzhezhilu/browser-image-conversion-dome)

**Comment by renzhezhilu** [comment]
看 #28
