### ISSUE TITLE
Gif -> WebP javascript api

### ISSUE THREAD

**Issue by didi789** [renzhezhilu/webp2jpg-online#23]
Can you provide Gif to WebP simple API?
Which get as input gif (base64) and return animated webP (base64 too)..

I want to use this in background thread, no UI needed.

**Comment by renzhezhilu** [comment]
hey, I just updated,you can look at [browser-image-conversion-dome](https://github.com/renzhezhilu/browser-image-conversion-dome) and [gif to webp demo](https://renzhezhilu.github.io/browser-image-conversion-dome/src/gifToWebp/gifToWebp.html)

**Comment by renzhezhilu** [comment]
Please note that the output webp is sometimes not perfect
