### ISSUE TITLE
我又重新搭了一遍，还是。。。我哭了

### ISSUE THREAD

**Issue by renzhezhilu** [renzhezhilu/webp2jpg-online#28]
imgedit.kejihub.com 我又重新搭了一遍，还是。。。我哭了

_Originally posted by @milu7 in https://github.com/renzhezhilu/webp2jpg-online/issues/27#issuecomment-886250103_

**Comment by milu7** [comment]
我是不是发错位置了。。。

**Comment by renzhezhilu** [comment]
不是，我单独出来了，你看看这个[webp2jpg demo](https://github.com/renzhezhilu/browser-image-conversion-dome)，页面做过处理，直接另存不行的，我把用到的模块都放上面那个项目 有兴趣研究吧

**Comment by renzhezhilu** [comment]
我的锅，我把readme更新下说清楚

**Comment by milu7** [comment]
一年前我把2.0放上去后，好像还能正常使用。（我不是很懂代码，只会。。。放上去，打开，OK。）

**Comment by milu7** [comment]
一直都是放二级目录下的，不知道为什么，有些奇怪的现象。。。感觉是某些文件没有调用上的感觉。。

**Comment by renzhezhilu** [comment]
> 一直都是放二级目录下的，不知道为什么，有些奇怪的现象。。。感觉是某些文件没有调用上的感觉。。

试试这个[iframe_v3](https://renzhezhilu.gitee.io/webp2jpg-online/iframe_v3.html),代码[iframe_v3_code](https://github.com/renzhezhilu/webp2jpg-online/blob/master/iframe_v3.html)
