### ISSUE TITLE
大佬，貌似在safari下无法转换webp呢

### ISSUE THREAD

**Issue by windyao** [renzhezhilu/webp2jpg-online#3]

**Comment by renzhezhilu** [comment]
不会啊，试了webp和webp动画都贼滑顺。
我的环境是
macOS High Sierra 版本10.13.6 (17G13035)
safari 版本 13.1.1 (13609.2.9.1.3)，
请提供更多信息，具体一点。

**Comment by renzhezhilu** [comment]
> _No description provided._

不会啊，试了webp和webp动画都贼滑顺。
我的环境是
macOS High Sierra 版本10.13.6 (17G13035)
safari 版本 13.1.1 (13609.2.9.1.3)，
请提供更多信息，具体一点。

**Comment by windyao** [comment]
我的环境是：
macOS Mojave 10.14
Safari 12.0 (14606.1.36.1.9)

请问你有给safari安装webp插件吗？

**Comment by renzhezhilu** [comment]
> 我的环境是：
> macOS Mojave 10.14
> Safari 12.0 (14606.1.36.1.9)
> 
> 请问你有给safari安装webp插件吗？

没有安装webp插件，Safari平时很少用。
不知道是不是版本的问题，你试试把Safari更新到最新（12.0->13），

**Comment by windyao** [comment]
> > 我的环境是：
> > macOS Mojave 10.14
> > Safari 12.0 (14606.1.36.1.9)
> > 请问你有给safari安装webp插件吗？
> 
> 没有安装webp插件，Safari平时很少用。
> 不知道是不是版本的问题，你试试把Safari更新到最新（12.0->13），

我更新不了。。

**Comment by renzhezhilu** [comment]
老铁,我刚刚才发现还真是不行!
Safari浏览器转webp，不要选`webp`,选`webp动画`即可
