### ISSUE TITLE
Can't lossless convert to avif.

### ISSUE THREAD

**Issue by starlight02** [renzhezhilu/webp2jpg-online#36]
操作系统：Windows 11 专业版 21H2
处理器：AMD 2920X
内存：32G

转换时一直呈现 Loading 状态，等了非常久（超过10分钟）还是在 Loading，发现 CPU 占有率还不到 10%。
原图为 14M 的 PNG 格式图片，尺寸为 5000*3536。

**Comment by renzhezhilu** [comment]
图片太大，应该超出worker的内存限制，
