### ISSUE TITLE
可以支持JXL格式吗

### ISSUE THREAD

**Issue by yeezylife** [renzhezhilu/webp2jpg-online#37]
现在MPV的截图支持JXL,不过想做壁纸还是得转换成JPG或者PNG
我想要用JXL这种压缩率更好的格式来保存图片,在需要的时候进行转换,不过我发现webp2jpg似乎不支持JXL的转换!

**Comment by renzhezhilu** [comment]
以后可能会加吧，现在你可以去[squoosh.app](https://squoosh.app/) 转换jxl
