### ISSUE TITLE
能否请您分享app_v3.2.1.js的原始解压代码

### ISSUE THREAD

**Issue by DarksydeTech** [renzhezhilu/webp2jpg-online#47]
我已经阅读了一些代码，对我来说似乎很有趣，但是有一点我很难阅读它，我会真诚地分享应用程序 v3.2.1.js 的原始代码，我认为它可以做更多的调整

**Comment by renzhezhilu** [comment]
不行，只提供使用 
更多请看 https://github.com/renzhezhilu/webp2jpg-online-demo
