### ISSUE TITLE
"New Version" less conversion formats?

### ISSUE THREAD

**Issue by katastrophe92** [renzhezhilu/webp2jpg-online#50]
Hello community! Thanks for this amazing tool! 

It is not complete the new version or are the other formats hidden?
![librewolf 21-21-33 12April2023](https://user-images.githubusercontent.com/103950507/231561496-58511afb-fc67-4921-a446-c006f554651f.png)

**Comment by renzhezhilu** [comment]
<img width="919" alt="image" src="https://github.com/renzhezhilu/webp2jpg-online/assets/7707921/bc71cc64-3c24-472a-801a-d7f9c78af331">
As shown in the picture, I just sorted by function

**Comment by katastrophe92** [comment]
@renzhezhilu but the .ico format is missing in the new version

**Comment by renzhezhilu** [comment]
Yes, I removed the .ico because the ico conversion function was unstable
