### ISSUE TITLE
GIF轉WEBP-ANIMATION會失敗

### ISSUE THREAD

**Issue by minimoonleaf** [renzhezhilu/webp2jpg-online#55]
GIF轉WEBP-ANIMATION會失敗
我使用的檔案如下https://drive.google.com/drive/folders/1fjQEV58vDq79eFdyBr5rAA9Gd-HfG_79?usp=sharing

**Comment by renzhezhilu** [comment]
使用新版转吧
https://imagestool.com/zh_CN/git-to-webp-to-apng.html
<img width="1027" alt="image" src="https://github.com/renzhezhilu/webp2jpg-online/assets/7707921/a672f692-3b60-4fb7-b8af-1a594be47e2a">

**Comment by minimoonleaf** [comment]
請問新版的只有線上版嗎?

**Comment by renzhezhilu** [comment]
是的，如果需要更专业的离线软件，可以雇我制作
