### ISSUE TITLE
网站挂了，每个功能页面点进去都提示无法使用

### ISSUE THREAD

**Issue by abcmiao** [renzhezhilu/webp2jpg-online#57]
![image](https://github.com/renzhezhilu/webp2jpg-online/assets/13944985/c1b199ec-496c-443d-9669-948470c91e83)

**Comment by renzhezhilu** [comment]
https://imagestool.com/zh_CN/compress-jpg-and-keep-exif

**Comment by abcmiao** [comment]
> https://imagestool.com/zh_CN/compress-jpg-and-keep-exif 去掉最后.html 应该就可以

好的，谢谢，老哥有兴趣打包成本地App吗？我觉得本地App会比网页好用

**Comment by abcmiao** [comment]
> https://imagestool.com/zh_CN/compress-jpg-and-keep-exif 去掉最后.html 应该就可以

你不处理一下吗老哥，每次使用都还得手动去掉后缀。十分麻烦呢

**Comment by abcmiao** [comment]
> 处理了下，现在应该可以了

还是不行呢老哥，你在看看

**Comment by abcmiao** [comment]
> 大概是缓存还没更新，你明天 先访问没有.html的 然后 多按几次ctrl+shitf+r 就可以了 信我

可以了，感谢
